
import { Objective } from './types';

const INITIAL_DATE = new Date().toISOString().split('T')[0];

export const INITIAL_OBJECTIVES: Objective[] = [
  // BLOQUE FUNCIONAMIENTO JD
  {
    id: 1,
    category: 'Funcionamiento JD',
    title: 'Diferenciar reuniones operativas VS debate/estrategia',
    description: 'Sintesis parte operativa para optimizar el tiempo de la junta.',
    status: 'Pending',
    priority: 'High',
    deadline: '2026-03-01',
    realDate: '',
    owner: 'Secretario',
    progress: 0,
    imageUrl: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&q=80&w=400',
    actions: [
      { id: 'a1', text: 'Definir agenda estándar para reuniones', isCompleted: false },
      { id: 'a2', text: 'Agendar sesiones trimestrales exclusivas de estrategia', isCompleted: false }
    ],
    comments: [],
    ease: 8,
    impact: 9,
    cost: 1,
    risk: 2
  },
  {
    id: 2,
    category: 'Funcionamiento JD',
    title: 'Definir canal de toma de decisiones rápidas',
    description: 'Establecer protocolo para decisiones vía encuesta WhatsApp o similar.',
    status: 'In Progress',
    priority: 'Medium',
    deadline: '2026-02-15',
    realDate: '',
    owner: 'Presidente',
    progress: 50,
    imageUrl: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&q=80&w=400',
    actions: [
      { id: 'a3', text: 'Crear grupo de WhatsApp exclusivo para votaciones', isCompleted: true },
      { id: 'a4', text: 'Redactar normativa de validez de voto digital', isCompleted: false }
    ],
    comments: [],
    ease: 9,
    impact: 7,
    cost: 1,
    risk: 3
  },
  {
    id: 3,
    category: 'Funcionamiento JD',
    title: 'Duración del mandato',
    description: 'Definir y consensuar estrategia a seguir respecto a los tiempos de la JD.',
    status: 'Pending',
    priority: 'Medium',
    deadline: '2026-06-01',
    realDate: '',
    owner: 'JD',
    progress: 0,
    imageUrl: 'https://images.unsplash.com/photo-1507537297725-24a1c434e3db?auto=format&fit=crop&q=80&w=400',
    actions: [],
    comments: [],
    ease: 5,
    impact: 6,
    cost: 1,
    risk: 5
  },
  // BLOQUE AREA SOCIAL (Antes Socios)
  {
    id: 4,
    category: 'Área Social',
    title: 'Estudiar acciones de diferenciación',
    description: 'Piscina, parking, toallas, etc. Crear valor añadido para el socio.',
    status: 'Pending',
    priority: 'Medium',
    deadline: '2026-04-01',
    realDate: '',
    owner: 'Comisión Social',
    progress: 0,
    imageUrl: 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?auto=format&fit=crop&q=80&w=400',
    actions: [],
    comments: [],
    ease: 4,
    impact: 8,
    cost: 7,
    risk: 4
  },
  {
    id: 5,
    category: 'Área Social',
    title: 'Calidad más que cantidad',
    description: 'Mejora de percepción de calidad. Evaluar necesidades y medición vía encuestas.',
    status: 'In Progress',
    priority: 'High',
    deadline: '2026-12-31',
    realDate: '',
    owner: 'Gerencia',
    progress: 20,
    imageUrl: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&q=80&w=400',
    actions: [
      { id: 'a5', text: 'Diseñar encuesta de satisfacción anual', isCompleted: true }
    ],
    comments: [],
    ease: 6,
    impact: 9,
    cost: 3,
    risk: 2
  },
  {
    id: 6,
    category: 'Área Social',
    title: 'Asamblea 2026',
    description: 'Evaluar cumplimiento peticiones Asamblea 2025. Evaluar próximo modelo de Asamblea.',
    status: 'Pending',
    priority: 'High',
    deadline: '2026-05-01',
    realDate: '',
    owner: 'JD',
    progress: 0,
    imageUrl: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&q=80&w=400',
    actions: [],
    comments: [],
    ease: 7,
    impact: 8,
    cost: 2,
    risk: 6
  },
  {
    id: 7,
    category: 'Área Social',
    title: 'Mejora comunicación',
    description: 'Nuevo modelo de Boletín informativo. Renovar web.',
    status: 'Pending',
    priority: 'Medium',
    deadline: '2026-09-01',
    realDate: '',
    owner: 'Marketing',
    progress: 0,
    imageUrl: 'https://images.unsplash.com/photo-1557200134-90327ee9fafa?auto=format&fit=crop&q=80&w=400',
    actions: [],
    comments: [],
    ease: 5,
    impact: 7,
    cost: 5,
    risk: 1
  },
  // BLOQUE AREA DEPORTIVA (Antes Deportiva)
  {
    id: 8,
    category: 'Área Deportiva',
    title: 'Mejora cualitativa escuelas Tenis',
    description: 'Elevar el nivel técnico y servicio de la escuela.',
    status: 'Pending',
    priority: 'High',
    deadline: '2026-09-01',
    realDate: '',
    owner: 'Director Deportivo',
    progress: 0,
    imageUrl: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?auto=format&fit=crop&q=80&w=400',
    actions: [],
    comments: [],
    ease: 3,
    impact: 10,
    cost: 6,
    risk: 5
  },
  {
    id: 9,
    category: 'Área Deportiva',
    title: 'Mejora gimnasio',
    description: 'Mejoras en instalaciones y revisión de horarios.',
    status: 'Pending',
    priority: 'Medium',
    deadline: '2026-04-01',
    realDate: '',
    owner: 'Gerencia',
    progress: 0,
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=400',
    actions: [],
    comments: [],
    ease: 6,
    impact: 6,
    cost: 8,
    risk: 2
  },
  // BLOQUE INSTALACIONES (Ahora Mantenimiento)
  {
    id: 10,
    category: 'Mantenimiento',
    title: 'Más mejoras visibles',
    description: 'Salto de calidad en la infraestructura general.',
    status: 'Pending',
    priority: 'Medium',
    deadline: '2026-12-31',
    realDate: '',
    owner: 'Mantenimiento',
    progress: 0,
    imageUrl: 'https://images.unsplash.com/photo-1581094794329-cd8119604f8b?auto=format&fit=crop&q=80&w=400',
    actions: [],
    comments: [],
    ease: 4,
    impact: 8,
    cost: 9,
    risk: 3
  },
  // BLOQUE AREA RRHH (Antes RRHH)
  {
    id: 11,
    category: 'Área RRHH',
    title: 'Evaluar cuellos de botella internos',
    description: 'Buscar acciones correctivas para desbloquear proyectos/iniciativas.',
    status: 'In Progress',
    priority: 'High',
    deadline: '2026-03-30',
    realDate: '',
    owner: 'RRHH',
    progress: 30,
    imageUrl: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&q=80&w=400',
    actions: [],
    comments: [],
    ease: 5,
    impact: 8,
    cost: 2,
    risk: 4
  },
  {
    id: 12,
    category: 'Área RRHH',
    title: 'Estudiar sistema de pagos con incentivos',
    description: 'Implementar variables por objetivos para el personal.',
    status: 'Pending',
    priority: 'High',
    deadline: '2026-01-30',
    realDate: '',
    owner: 'Tesorero',
    progress: 0,
    imageUrl: 'https://images.unsplash.com/photo-1554224155-98406852d009?auto=format&fit=crop&q=80&w=400',
    actions: [],
    comments: [],
    ease: 2,
    impact: 9,
    cost: 6,
    risk: 7
  },
  // BLOQUE AREA FINANCIERA (Antes Financiero)
  {
    id: 13,
    category: 'Área Financiera',
    title: 'Presupuesto base anual realista',
    description: 'Establecimiento de un presupuesto ajustado a la realidad actual.',
    status: 'Completed',
    priority: 'High',
    deadline: '2025-12-15',
    realDate: '2025-12-20',
    owner: 'Tesorero',
    progress: 100,
    imageUrl: 'https://images.unsplash.com/photo-1554224154-260327c00c40?auto=format&fit=crop&q=80&w=400',
    actions: [],
    comments: [{id: 'c1', author: 'Admin', text: 'Presupuesto aprobado en última reunión', timestamp: '2025-12-20'}],
    ease: 6,
    impact: 10,
    cost: 2,
    risk: 8
  },
  {
    id: 14,
    category: 'Área Financiera',
    title: 'Análisis rentabilidad Prahna Holistico',
    description: 'Revisión de cuentas y retorno del servicio Prahna.',
    status: 'Pending',
    priority: 'Low',
    deadline: '2026-06-30',
    realDate: '',
    owner: 'Gerencia',
    progress: 0,
    imageUrl: 'https://images.unsplash.com/photo-1543286386-2e659306cd6c?auto=format&fit=crop&q=80&w=400',
    actions: [],
    comments: [],
    ease: 7,
    impact: 4,
    cost: 2,
    risk: 1
  },
  {
    id: 15,
    category: 'Área Financiera',
    title: 'Mejora sistemas informáticos financieros',
    description: 'Mejorar la información financiera disponible mediante software.',
    status: 'Delayed',
    priority: 'Medium',
    deadline: '2026-02-01',
    realDate: '',
    owner: 'IT / Admin',
    progress: 10,
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=400',
    actions: [],
    comments: [],
    ease: 5,
    impact: 7,
    cost: 5,
    risk: 3
  }
];

export const CATEGORIES = [
  'Funcionamiento JD',
  'Área Social',
  'Área Deportiva',
  'Mantenimiento',
  'Área RRHH',
  'Área Financiera'
];

export const STATUS_COLORS = {
  'Pending': 'bg-gray-100 text-gray-600',
  'In Progress': 'bg-blue-100 text-blue-700',
  'Completed': 'bg-green-100 text-green-700',
  'Delayed': 'bg-red-100 text-red-700'
};

export const PRIORITY_COLORS = {
  'Low': 'bg-slate-100 text-slate-600',
  'Medium': 'bg-yellow-100 text-yellow-700',
  'High': 'bg-orange-100 text-orange-700'
};
